name: Deploy NuGet Packages

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build and pack T2t.Barcode.Drawing
      run: |
        cd src/T2t.Barcode.Drawing
        dotnet restore --source "https://api.nuget.org/v3/index.json"
        dotnet build --configuration Release --no-restore --version "${{ github.ref_name }}"
        dotnet pack --configuration Release --output ../nupkg --version "${{ github.ref_name }}"

    - name: Build and pack T2t.Barcode.Skia
      run: |
        cd src/T2t.Barcode.Skia
        dotnet restore --source "https://api.nuget.org/v3/index.json" 
        dotnet build --configuration Release --no-restore --version ${{ github.ref_name }}
        dotnet pack --configuration Release --output ../nupkg --version ${{ github.ref_name }}

    - name: Build and pack T2t.Barcode.Svg
      run: |
        cd src/T2t.Barcode.Svg
        dotnet restore --source "https://api.nuget.org/v3/index.json"
        dotnet build --configuration Release --no-restore --version ${{ github.ref_name }}
        dotnet pack --configuration Release --output ../nupkg --version ${{ github.ref_name }}

    # 
    # dotnet nuget add source -u sinsedrix -p ${{ secrets.PKGREG_TOKEN }} --name nuget.org "https://nuget.pkg.github.com/tool2team/index.json"
    - name: Publish to NuGet and Github
      run: |
        ls nupkg/*
        dotnet nuget push "./nupkg/*.nupkg" --source "https://nuget.pkg.github.com/tool2team/index.json" --api-key ${{ secrets.PKGREG_TOKEN }} 
        dotnet nuget add source -u sinsedrix -p ${{ secrets.NUGET_API_KEY }} --name nuget.org "https://api.nuget.org/v3/index.json"
        dotnet nuget push "./nupkg/*.nupkg" --source "https://api.nuget.org/v3/index.json"