name: Deploy NuGet Packages

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build and pack T2t.Barcode.Drawing
      run: |
        dotnet restore --source "https://api.nuget.org/v3/index.json" src/T2t.Barcode.Drawing/T2t.Barcode.Drawing.csproj
        dotnet build --configuration Release --no-restore src/T2t.Barcode.Drawing/T2t.Barcode.Drawing.csproj
        dotnet pack --configuration Release --output nupkg src/T2t.Barcode.Drawing/T2t.Barcode.Drawing.csproj

    - name: Build and pack T2t.Barcode.Skia
      run: |
        dotnet restore --source "https://api.nuget.org/v3/index.json" src/T2t.Barcode.Skia/T2t.Barcode.Skia.csproj
        dotnet build --configuration Release --no-restore src/T2t.Barcode.Skia/T2t.Barcode.Skia.csproj
        dotnet pack --configuration Release --output nupkg src/T2t.Barcode.Skia/T2t.Barcode.Skia.csproj

    - name: Build and pack T2t.Barcode.Svg
      run: |
        dotnet restore --source "https://api.nuget.org/v3/index.json" src/T2t.Barcode.Svg/T2t.Barcode.Svg.csproj
        dotnet build --configuration Release --no-restore src/T2t.Barcode.Svg/T2t.Barcode.Svg.csproj
        dotnet pack --configuration Release --output nupkg src/T2t.Barcode.Svg/T2t.Barcode.Svg.csproj

    - name: Set NuGet API Key
      run: echo "//nuget.org/api/v2/:API_KEY" > nuget.config
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Publish to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --source "https://api.nuget.org/v3/index.json"